---
- name: Preparation of node
  ansible.builtin.include_tasks: host-prep.yml

- name: Installation in online environment for server
  ansible.builtin.include_tasks: installation-server.yml
  when: inventory_hostname in groups['server']

- name: Installation in online environment for agent
  ansible.builtin.include_tasks: installation-agent.yml
  when: inventory_hostname in groups['agent']
